import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import path from "path";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const TiktokSans = localFont({
  src: [
    {
      path : '../public/fonts/TikTokSans_18pt_Condensed-Black.ttf',
      weight: '900',
      style: 'normal',
    },
    {
      path : '../public/fonts/TikTokSans_18pt_Condensed-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path : '../public/fonts/TikTokSans_18pt_Condensed-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path : '../public/fonts/TikTokSans_18pt_Condensed-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path : '../public/fonts/TikTokSans_18pt_Condensed-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path : '../public/fonts/TikTokSans_18pt_Condensed-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path : '../public/fonts/TikTokSans_18pt_Condensed-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${TiktokSans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
